# Generated by Django 5.1.6 on 2025-03-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_the_letter', models.CharField(blank=True, max_length=100, null=True, verbose_name='subject of the letter')),
                ('letter_body', models.TextField(blank=True, null=True, verbose_name='letter body')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full Name')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('end_sent_at', models.DateTimeField(verbose_name='date and time ending')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=10, verbose_name='status')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='message')),
                ('recipients', models.ManyToManyField(to='mailing.recipient', verbose_name='recipients')),
            ],
        ),
    ]
